name: chat_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  camera: ^0.11.1
  emoji_picker_flutter: ^4.3.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0
  path_provider: ^2.1.5
  path:
  video_player: ^2.9.5
  socket_io_client: ^3.1.2
  flutter_otp_text_field: ^1.5.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/
   - assets/status/
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Bold.ttf
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-Italic.ttf
          style: italic

