// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_kbwh1cFnQmvKOjbw1GeOMBBK7wonU7g',
    appId: '1:241932888383:web:4a9073b4717757302e0b8a',
    messagingSenderId: '241932888383',
    projectId: 'whatsapp-clone-c356a',
    authDomain: 'whatsapp-clone-c356a.firebaseapp.com',
    storageBucket: 'whatsapp-clone-c356a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwQAYeNmXKLknHyF0EUuMFkwcUOX884YE',
    appId: '1:241932888383:android:ff84e69e92dc6a572e0b8a',
    messagingSenderId: '241932888383',
    projectId: 'whatsapp-clone-c356a',
    storageBucket: 'whatsapp-clone-c356a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCaVLD2V2vNzFOhbTHY6KVZEbFnERJMjc',
    appId: '1:241932888383:ios:c67fe5f6ee5852792e0b8a',
    messagingSenderId: '241932888383',
    projectId: 'whatsapp-clone-c356a',
    storageBucket: 'whatsapp-clone-c356a.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCaVLD2V2vNzFOhbTHY6KVZEbFnERJMjc',
    appId: '1:241932888383:ios:c67fe5f6ee5852792e0b8a',
    messagingSenderId: '241932888383',
    projectId: 'whatsapp-clone-c356a',
    storageBucket: 'whatsapp-clone-c356a.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_kbwh1cFnQmvKOjbw1GeOMBBK7wonU7g',
    appId: '1:241932888383:web:3a799f044a1292982e0b8a',
    messagingSenderId: '241932888383',
    projectId: 'whatsapp-clone-c356a',
    authDomain: 'whatsapp-clone-c356a.firebaseapp.com',
    storageBucket: 'whatsapp-clone-c356a.firebasestorage.app',
  );
}
